name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Create Docker network for running Testcontianers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
